### ISSUE TITLE
Incompatibility with sphinx master

### ISSUE THREAD

**Issue by mglisse** [sqlalchemyorg/sphinx-paramlinks#3]
Hello,
I tried using sphinx from the master branch on github (they just fixed a bug I was interested in) and noticed that sphinx_paramlinks isn't working for me anymore, even if I use the current master branch. Using a simple test file a.py
```python
def f(X):
    """
    :param X: Something
    """
    pass
```
index.rst
```rst
.. toctree::
   :maxdepth: 2
   :caption: Contents:

.. autofunction:: a.f
```
and with `extensions = [ 'sphinx.ext.autodoc', 'sphinx_paramlinks' ]` in conf.py, building the html doc shows
<pre>
Exception occurred:
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/domains/python.py", line 1327, in get_objects
    if obj.objtype != 'module':  # modules are already handled
AttributeError: 'tuple' object has no attribute 'objtype'
</pre>
The full traceback:
<pre>
# Sphinx version: 3.1.0+
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10.1
# Last messages:
#   writing additional pages...
#   search
#   done
#   copying static files... ...
#   done
#   copying extra files...
#   done
#   dumping search index in English (code: en)...
#   failed
#   The name of the builder is: html
# Loaded extensions:
#   sphinx.ext.mathjax (3.1.0+) from /home/glisse/.local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/glisse/.local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/glisse/.local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/glisse/.local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/glisse/.local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/glisse/.local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.1.0+) from /home/glisse/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.1.0+) from /home/glisse/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx_paramlinks (unknown version) from /home/glisse/.local/lib/python3.8/site-packages/sphinx_paramlinks/__init__.py
Traceback (most recent call last):
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 364, in build
    self.finish()
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 622, in finish
    self.handle_finish()
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1043, in handle_finish
    self.finish_tasks.add_task(self.dump_search_index)
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1058, in dump_search_index
    self.indexer.dump(ft, self.indexer_format)
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/search/__init__.py", line 320, in dump
    format.dump(self.freeze(), stream)
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/search/__init__.py", line 378, in freeze
    objects = self.get_objects(fn2index)  # populates _objtypes
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/search/__init__.py", line 329, in get_objects
    sorted(domain.get_objects()):
  File "/home/glisse/.local/lib/python3.8/site-packages/sphinx/domains/python.py", line 1327, in get_objects
    if obj.objtype != 'module':  # modules are already handled
AttributeError: 'tuple' object has no attribute 'objtype'
</pre>

**Comment by zzzeek** [comment]
OK well they are released on the 3.0.x series for now and it is common that my extensions break when new releases come out.    I need to keep them working in order to build sqlalchemy's docs so this will certainly get fixed at some point.  if you have interest in submitting a PR feel free.

**Comment by zzzeek** [comment]
perhaps there's a tuple here we are creating that's now a named tuple.  will look

**Comment by zzzeek** [comment]
okey doke, can you try this patch?  this works wtih current 3.0.x and should fix the 3.1 problem but i didnt test w/ master yet
```

diff --git a/sphinx_paramlinks/sphinx_paramlinks.py b/sphinx_paramlinks/sphinx_paramlinks.py
index 763a1ff..56f42b2 100644
--- a/sphinx_paramlinks/sphinx_paramlinks.py
+++ b/sphinx_paramlinks/sphinx_paramlinks.py
@@ -15,6 +15,13 @@ from sphinx import __version__
 from sphinx.domains import ObjType
 from sphinx.util import logging
 
+try:
+    # coming up in 3.1
+    from sphinx.domains.python import ObjectEntry
+except:
+    from collections import namedtuple
+    ObjectEntry = namedtuple('ObjectEntry', ['docname', 'node_id', 'objtype'])
+
 PythonDomain.object_types["parameter"] = ObjType("parameter", "param")
 
 LOG = logging.getLogger(__name__)
@@ -74,6 +81,7 @@ def autodoc_process_docstring(app, what, name, obj, options, lines):
             )
             if LooseVersion(__version__) >= LooseVersion("1.4.0"):
                 item += (None,)
+
             doc_idx.append(item)
             return ":param %s_sphinx_paramlinks_%s.%s:" % (
                 modifier,
@@ -265,7 +273,7 @@ def build_index(app, doctree):
         if LooseVersion(__version__) >= LooseVersion("3.0.0"):
             for entry in doc_entries:
                 sing, desc, ref, extra = entry[:4]
-                app.env.domains["py"].data["objects"][ref] = (
+                app.env.domains["py"].data["objects"][ref] = ObjectEntry(
                     docname,
                     ref,
                     "parameter",

```

**Comment by zzzeek** [comment]
worked on this end for master although master seems to have broken multiprocessing, hope they fix that

**Comment by mglisse** [comment]
Thanks!
