### ISSUE TITLE
Import error ObjectEntry in 0.5.0 for ReadTheDocs

### ISSUE THREAD

**Issue by fmigneault** [sqlalchemyorg/sphinx-paramlinks#5]
`sphinx-paramlinks-0.5.0` installed on ReadTheDocs breaks with following traceback. 
The fixes described in #3 somehow make their way up?

````
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx_paramlinks/__init__.py", line 3, in <module>
    from .sphinx_paramlinks import setup  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx_paramlinks/sphinx_paramlinks.py", line 11, in <module>
    from sphinx.domains.python import ObjectEntry
ImportError: cannot import name 'ObjectEntry' from 'sphinx.domains.python' (/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/domains/python.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 405, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_paramlinks (exception: cannot import name 'ObjectEntry' from 'sphinx.domains.python' (/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/domains/python.py))

Extension error:
Could not import extension sphinx_paramlinks (exception: cannot import name 'ObjectEntry' from 'sphinx.domains.python' (/home/docs/checkouts/readthedocs.org/user_builds/pavics-magpie/envs/latest/lib/python3.7/site-packages/sphinx/domains/python.py))
```

**Comment by zzzeek** [comment]
I dropped support for older versions of Sphinx so you would want to make sure you use Sphinx 3.1 or greater.   RTD should allow you to use any sphinx version you want.
