### ISSUE TITLE
Error with Sphinx 4?

### ISSUE THREAD

**Issue by astrojuanlu** [sqlalchemyorg/sphinx-paramlinks#9]
From https://github.com/PyTorchLightning/pytorch-lightning/issues/7455:

```
Extension error (sphinx_paramlinks.sphinx_paramlinks):
Handler <function build_index at 0x7f20c201c820> for event 'doctree-read' threw an exception (exception: __new__() missing 1 required positional argument: 'aliased')
make: *** [Makefile:19: html] Error 2
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
RuntimeError: Build failed
```

**Comment by Borda** [comment]
@astrojuanlu Thank you for taking care about it :]

**Comment by zzzeek** [comment]
im sure i will have a lot of things to fix w/ my plugins + sphinx 4 that seems to have been released yesterday.   will try to work through them tomorrow.

**Comment by akihironitta** [comment]
@zzzeek Thank you for fixing this so quickly!
